// File generated by WebFX (DO NOT EDIT MANUALLY)

module webfx.lib.reusablestream {

    // Direct dependencies modules
    requires java.base;

    // Exported packages
    exports dev.webfx.tools.util.reusablestream;
    exports dev.webfx.tools.util.reusablestream.impl;

}